/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as GitRouteImport } from './routes/git'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsSyncRouteImport } from './routes/skills-sync'
import { Route as StatusRouteImport } from './routes/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const GitRoute = GitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSyncRoute = SkillsSyncRouteImport.update({
  id: '/skills-sync',
  path: '/skills-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/git': typeof GitRoute
  '/projects': typeof ProjectsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/settings': typeof SettingsRoute
  '/skills-sync': typeof SkillsSyncRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/git': typeof GitRoute
  '/projects': typeof ProjectsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/settings': typeof SettingsRoute
  '/skills-sync': typeof SkillsSyncRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/git': typeof GitRoute
  '/projects': typeof ProjectsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/settings': typeof SettingsRoute
  '/skills-sync': typeof SkillsSyncRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/git'
    | '/projects'
    | '/screenshots'
    | '/settings'
    | '/skills-sync'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/git'
    | '/projects'
    | '/screenshots'
    | '/settings'
    | '/skills-sync'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/git'
    | '/projects'
    | '/screenshots'
    | '/settings'
    | '/skills-sync'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  GitRoute: typeof GitRoute
  ProjectsRoute: typeof ProjectsRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsSyncRoute: typeof SkillsSyncRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git': {
      id: '/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof GitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-sync': {
      id: '/skills-sync'
      path: '/skills-sync'
      fullPath: '/skills-sync'
      preLoaderRoute: typeof SkillsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  GitRoute: GitRoute,
  ProjectsRoute: ProjectsRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  SettingsRoute: SettingsRoute,
  SkillsSyncRoute: SkillsSyncRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
